FROM ubuntu:20.04

ENV CMAKE_VERSION=3.21.0
ENV PYTHON_VERSION=3.10.11

RUN echo "Installing apt packages..." \
	&& export DEBIAN_FRONTEND=noninteractive \
	&& apt -y update --no-install-recommends \
	&& apt -y install --no-install-recommends \
	build-essential \
	g++ \
    wget \
    python-dev-is-python3 \
    python3-pip \
    autotools-dev \
    libicu-dev \
    libbz2-dev \
    libboost-all-dev \
    && apt autoremove -y \
	&& apt clean -y \
	&& export DEBIAN_FRONTEND=dialog

RUN echo "Installing pip packages..." \
	#&& pip3 --no-cache-dir install -r ./requirements.txt \
	&& pip --no-cache-dir install cmake==${CMAKE_VERSION} numpy
	#&& rm ./requirements.txt

# https://boostorg.jfrog.io/artifactory/main/release/1.75.0/source/boost_1_75_0.tar.gz
COPY ./boost_1_75_0.tar.gz ./  

RUN echo "Installing boost..." \
    && tar -xzf boost_1_75_0.tar.gz \
    && rm ./boost_1_75_0.tar.gz \
    && cd ./boost_1_75_0 \
    && ./bootstrap.sh --prefix=/usr/ --with-libraries=python \
    && ./b2 install \
    && cd .. \
    && rm -r ./boost_1_75_0